"""
Django settings for Mgt project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
from django.core.exceptions import ImproperlyConfigured

def get_env(var_name):
    try:
        return os.environ[var_name]
    except KeyError:
        raise ImproperlyConfigured(f"Missing required env var `{var_name}`")
    

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APPNAME = get_env("APPNAME")
DBNAME = get_env("DBNAME")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

SUPERUSER = get_env("DJANGO_SUPERUSER")
SECRET_KEY = get_env("DJANGO_SECRET_KEY") # CHANGE to new secret key 

DEBUG = True

# 'DJANGO_ALLOWED_HOSTS' should be a single string of hosts with a space between each.
# For example: 'DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]'
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', '0.0.0.0', '[::1]', '*']

INSTALLED_APPS = [
    APPNAME, # CHANGE add new databases to this list. 
    'django_tables2',
    'Home',
    'MGTdb_shared',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'rest_framework',
	'django_registration',
	'django_countries',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Mgt.urls_template' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Home/templates/'), os.path.join(BASE_DIR, 'Home/templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
				'Mgt.context_processors.root_url',
            ],
        },
    },
]

TEMPLATE_DEBUG = True

TEMPLATE_LOADERS = (
    'django.template.loaders.app_directories.load_template_source',
)

MANAGEMENT_COMMANDS = ['Mgt.management.commands.show_urls']

MY_URL = get_env("MGT_URL")

WSGI_APPLICATION = 'Mgt.wsgi.application'

FILE_UPLOAD_PERMISSIONS=0o774
FILE_UPLOAD_DIRECTORY_PERMISSIONS=0o774

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# 2018, Jan 9 - require a db router (if multiple databases)
NCBI_RETRIEVAL_FREQUENCY = {'`Species`': None} # CHANGE to frequency of retrieval

DATABASE_ROUTERS = ['Mgt.router.GenericRouter']
APPS_DATABASE_MAPPING = {APPNAME:DBNAME} #CHANGE change to appname in INSTALLED_APPS and database DATABASES in name normally upper and lowercase first letter i.e. Salmonella and salmonella

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "USER": get_env("POSTGRES_USER"), 
        "PASSWORD": get_env("POSTGRES_PASSWORD"), 
        "HOST": get_env("POSTGRES_HOST"), 
        "PORT": get_env("POSTGRES_PORT"), 
        'NAME': 'default',
    },
    ## Database configuration example 
    # # 'blankdb': { # CHANGE postgres database name
    # #     'ENGINE': 'django.db.backends.postgresql',
    # #     'HOST': '0.0.0.0',
    # #     'PORT': '5432',
    # #     'USER': 'blankuser', #CHANGE add postgres user
    # #     'PASSWORD': 'blankpassword', #CHANGE add postgres password
    # #     'NAME': 'blankdb',#CHANGE to new database name
    # # },
    ## Clawclip example 
    DBNAME: {
        "ENGINE": "django.db.backends.postgresql",
        "USER": get_env("POSTGRES_USER"), 
        "PASSWORD": get_env("POSTGRES_PASSWORD"), 
        "HOST": get_env("POSTGRES_HOST"), 
        "PORT": get_env("POSTGRES_PORT"), 
        'NAME': DBNAME, 
    },
}

NONLOCALHOST='0.0.0.0' # leave as 0.0.0.0 for local install

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# added_on: 2018, Feb 8 - for HMAC activation workflow
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window;
INCLUDE_REGISTER_URL = True
REGISTRATION_OPEN = True
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", 10))
LOGIN_REDIRECT_URL = '/'

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)



#RELATIVE PATHS FROM folder containing manage.py in this repo to folder on your system
# NOTE: Please move the data folders to a secure location once setup is complete.  
SUBDIR_REFERENCES = '../../Mgt/Mgt/References/' 
SUBDIR_ALLELES = '../../Mgt/Mgt/Alleles/' 
MEDIA_ROOT = '../../Mgt/Mgt/Uploads/'
BLASTALLELES='../../Mgt/Mgt/species_specific_alleles/'

# ABSOLUTE PATH VERSIONS OF ABOVE
ABS_SUBDIR_REFERENCES = os.path.join(BASE_DIR, 'References/')
ABS_SUBDIR_ALLELES = os.path.join(BASE_DIR, 'Alleles/')
ABS_MEDIA_ROOT = os.path.join(BASE_DIR, 'Uploads/')
ABS_BLASTALLELES= os.path.join(BASE_DIR, 'species_specific_alleles/')

FILES_FOR_DOWNLOAD = os.path.join(BASE_DIR, 'files_for_download/')
TMPFOLDER = os.path.join(BASE_DIR, 'tmp_files/')

RTOA_DEFAULTS = os.path.join(BASE_DIR, 'MGT_processing/Reads2MGTAlleles/rtoa_defaults.json')


ASCPKEY = "/Path/to/.aspera/connect/etc/asperaweb_id_dsa.openssh"#CHANGE ONLY NEEDED IF RUNNING cron_pipeline --dl_reads

KRAKEN_DEFAULT_DB='/home/mgt/minikraken_20171019_8GB/'#CHANGE ONLY NEEDED IF RUNNING cron_pipeline --reads_to_alleles

### NOT NEEDED ON LOCAL DB ###
KATANA_LOCATION=''
TESTDB="True"
KATANA_SETTINGS=''
##############################

if DEBUG:
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

#CHANGE BELOW TO list species specific cutoffs/values
SPECIES_SEROVAR = {APPNAME: {"species":'Xanthomonas citri',
                                  "serovar":'',
                                  "min_largest_contig":60000,
                                  "max_contig_no":700,
                                  "n50_min":20000,
                                  "genome_min":4500000,
                                  "genome_max":6000000,
                                  "hspident":0.90,
                                  "locusnlimit":0.8,
                                  "snpwindow":40,
                                  "densitylim":16,
                                  "refsize":5.0,
                                  "blastident":85,
                                  "apzero":0.04
                                  }
                   }

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATE_FORMAT = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'Static/'

RAWQUERIES_DISPLAY = {APPNAME: '', } # CHANGE for extra queries in database but keep string empty if using default (i.e, 'Salmonella': '')
